#!/usr/bin/env python3
"""
  Knowledge Journal - Project Euler - Problem 2 - Even Fibonacci Numbers  

  Copyright (c) 2026, Augusto Damasceno.
  All rights reserved.

  SPDX-License-Identifier: BSD-2-Clause
"""

__author__ = "Augusto Damasceno"
__version__ = "1.0"
__copyright__ = "Copyright (c) 2026, Augusto Damasceno."
__license__ = "BSD-2-Clause"


def main():
    '''
    https://projecteuler.net/problem=2
    Each new term in the Fibonacci sequence is generated by adding 
    the previous two terms. By starting with 1 and 2, 
    the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values 
    do not exceed four million, find the sum of the even-valued terms.
    '''

    # Observe the pattern ... even, odd, odd, even ...
    # A case with two know evens A and B and all other variables unknow
    #   A, x1, x2, B, x3, x4, C
    #   C = x4 + x3
    #   C = (x3 + B) + (B + x2)
    #   C = (B + x2) + B + B + (x1 + A)
    #   C = 3B + x1  + x2 + A
    #   C = 3B + B + A
    #   C = 4B + A
    c = 2
    a, b = 2, 8
    while b <= 4000000:
        c += b
        a, b = b, 4 * b + a

    return c


if  __name__ == "__main__":
    result = main()
    print(f"Knowledge Journal - Project Euler - Problem 2: {result}")